### ISSUE TITLE
has link libmariacpp.a but report undefined error

### ISSUE THREAD

**Issue by Hardy5012** [Roslaniec/MariaCpp#1]
I am sure my project has link libmariacpp.a

> ../../bin/libcommon.so: undefined reference to `mysql_close'
> ../../bin/libcommon.so: undefined reference to`MariaCpp::library_init()'
> ../../bin/libcommon.so: undefined reference to `MariaCpp::Uri::Uri(std::string const&)'
> ../../bin/libcommon.so: undefined reference to`MariaCpp::library_end()'
> ../../bin/libcommon.so: undefined reference to `MariaCpp::Connection::connect(MariaCpp::Uri const&, char const*, char const*, unsigned long)'
> ../../bin/libmanager.so: undefined reference to`MariaCpp::Connection::~Connection()'
> ../../bin/libcommon.so: undefined reference to `MariaCpp::Connection::Connection()'

**Comment by Hardy5012** [comment]
> cd /home/huaming_li/github/lytz/Quota_Repo/stockbs_svr/build/stockbs_svr/server && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/sps_server.dir/link.txt --verbose=1
> g++    -std=c++11   -Wno-invalid-offsetof -Wno-unused -Wno-sign-compare -Wno-switch -Wno-format  -DBOOST_ALL_DYN_LINK -DGROUND_ENABLE_FILE_LOG -DGROUND_ENABLE_MULTI_THREAD  -g -g   CMakeFiles/sps_server.dir/main.cc.o CMakeFiles/sps_server.dir/bs_config.cc.o CMakeFiles/sps_server.dir/bs_application.cc.o CMakeFiles/sps_server.dir/bs_context.cc.o CMakeFiles/sps_server.dir/bs_server.cc.o CMakeFiles/sps_server.dir/bs_server_session.cc.o  -o ../../bin/sps_server  -L/usr/local/lib/mariadb  -L/usr/local/lib  -L/usr/local/protobuf/lib  -L/home/huaming_li/github/lytz/Quota_Repo/stockbs_svr/lib -rdynamic -lprotobuf -lprotobuf-lite -lprotoc -lboost_atomic -lboost_program_options -lboost_date_time -lboost_filesystem -lboost_log -lboost_regex -lboost_thread -lboost_system -lboost_chrono -lboost_locale -lpthread -lredisclient -lmariadb -lmariacpp ../../bin/libcommon.so ../../bin/libdao.so ../../bin/libclient.so ../../bin/liblyproto.so ../../bin/libcalculate.so ../../bin/libmanager.so -Wl,-rpath,/usr/local/lib/mariadb:/usr/local/lib:/usr/local/protobuf/lib:/home/huaming_li/github/lytz/Quota_Repo/stockbs_svr/lib:/home/huaming_li/github/lytz/Quota_Repo/stockbs_svr/build/bin 
> ../../bin/libcommon.so: undefined reference to `MariaCpp::library_init()'
> ../../bin/libcommon.so: undefined reference to`MariaCpp::Uri::Uri(std::string const&)'
> ../../bin/libcommon.so: undefined reference to `MariaCpp::library_end()'
> ../../bin/libcommon.so: undefined reference to`MariaCpp::Connection::connect(MariaCpp::Uri const&, char const_, char const_, unsigned long)'
> ../../bin/libmanager.so: undefined reference to `MariaCpp::Connection::~Connection()'
> ../../bin/libcommon.so: undefined reference to`MariaCpp::Connection::Connection()'
> collect2: error: ld returned 1 exit status

**Comment by Roslaniec** [comment]
The order of linking is important. You must put it after libcommon.so and libmanager.so like this:
../../bin/libcommon.so ../../bin/libmanager.so -lmariacpp -lmariadb

BTW: because you are using shared libraries, you might consider to build mariacpp as shared lib as well (in src/CMakeLists.txt change the word STATIC into SHARED).
