### ISSUE TITLE
Linking with mariadb-connector-c 3.0 fails

### ISSUE THREAD

**Issue by mezon525** [Roslaniec/MariaCpp#2]
There are two problems when linking mariacpp with mariadb-connector-c 3.0.x.
- mysql_create_db() and mysql_drop_db() have been deprecated.
- SQLSTATE_UNKNOWN is not included in libmariadb.so

I tried to correct the code and it seems successful.
Is this OK? Please confirm and I hope some kind of corrections would be merged in the master.

sed -i -e '69i\#if 0 // deprecated since mariadb 3.0.0' \
    -e '74i\#endif' mariacpp/connection.hpp
sed -i 's/SQLSTATE_UNKNOWN/"HY000"/' src/bind.cpp

**Comment by Roslaniec** [comment]
Thank you for your report.
I have applied your changes and committed into master.
