### ISSUE TITLE
Any chance this might support the non-blocking mariadb API?

### ISSUE THREAD

**Issue by BluBb-mADe** [Roslaniec/MariaCpp#4]
Is there any chance this might support the [non-blocking API](https://mariadb.com/kb/en/library/using-the-non-blocking-library/) at some point?
I am in a weak-client-strong-server scenario and would like to save on threads on the client and instead just do a connection pool.
I would even be willing to do some of the legwork but I don't think I could fit a non-blocking API into the existing wrapper in an acceptable way. (I am not very happy with my architecture skills.)

I really like this wrapper. It looks clean and intuitive and who doesn't like RAII or proper error handling.

**Comment by Roslaniec** [comment]
I would love to add non-blocking API support. I was already considering it long time ago, but really had no strong motivation, because multiple-threads model worked very well for me. 
I will keep this ticket open.
But please do not expect this to be implemented very soon.

**Comment by Roslaniec** [comment]
Support for non-blocking API was added with last commit.
