### ISSUE TITLE
Support Transaction

### ISSUE THREAD

**Issue by hoangtrucit** [Roslaniec/MariaCpp#5]
i see you set `set autocommit=1` when init connection so you have plan support transaction ?

**Comment by Roslaniec** [comment]
Transactions are supported from the beginning.
You can do:
conn->query("START TRANSACTION");
....
conn->commit();

Alternatively you can disable autocommit permanently with autocommit(false) and commit every query/transaction.
More info here: https://mariadb.com/kb/en/library/start-transaction/
