### ISSUE TITLE
isClosed()

### ISSUE THREAD

**Issue by howudodat** [Roslaniec/MariaCpp#6]
is there an equivalent to mysqlconncpp isClosed() function?

**Comment by Roslaniec** [comment]
No.
If you really need to remember if you called "close()" method before, you need to store this information elsewhere.
But actually calling Connection.close() is not needed: Connection will be closed automatically on Connection destruction. 
Also it is allowed to call close() many times.

**Comment by howudodat** [comment]
Connections can get closed for other reasons than calling close()  (ie: server dies, network goes away and comes back, et al).  Our application creates a connection pool and leaves those connections open because we are doing thousands of transactions per second.  Knowing if the connection has gone away is important.

**Comment by Roslaniec** [comment]
To verify if network connection is still valid and server responding, you should use Connection::ping() method.

I guess your expectations regarding isClose() method are not valid.

This is quote from: Changes in MySQL Connector/C++ 1.1.5 (2014-11-26, General Availability)

    Connector/C++ issued a ping command every time |isClosed()| was called in a |Connection|, rather than just checking whether |close()| had been called earlier or when a fatal error occurred in an earlier operation. (Bug #69785, Bug #17186530)

https://dev.mysql.com/doc/relnotes/connector-cpp/en/news-1-1-5.html

**Comment by howudodat** [comment]
Thank you!
