### ISSUE TITLE
resultset

### ISSUE THREAD

**Issue by howudodat** [Roslaniec/MariaCpp#7]
(sorry still learning this framework after years of using mysqlcppconn)
Normally I would do statement->executeQuery which returned a resultset that I would iterate over. 
```
	unique_ptr<sql::PreparedStatement> pstmt(conn->prepareStatement(sSql));
	unique_ptr<sql::ResultSet> rs(pstmt->executeQuery());
	return rs;
```
I dont see a similar function.  
I see that I can use statement->fetch.

**Comment by Roslaniec** [comment]
It is very beneficial to read Connector/C API docs: https://dev.mysql.com/doc/refman/8.0/en/mysql-stmt-fetch.html
Simply: PreparedStatement works with fetch()

ResultSets (eg. mysql_store_result()) are used after simple queries:
https://dev.mysql.com/doc/refman/8.0/en/mysql-store-result.html

Notice that Connector/C++ was designed around JDBC API. 
In it's code I see, that MySQL_Prepared_ResultSet::next() is just a wrapper around PreparedStatement.fetch() method.

**Comment by howudodat** [comment]
thanks I'll take a look at those docs.  I'm migrating our existing app and just trying not to have to unwind too much code.  So far so good, just 2x checking on things that aren't mapping.

I have one more question that I can post into another issue if you want, but I'll put it here too:
Is there any way to do something like:
int id = statement->getInt("ID") instead of getInt(0)

**Comment by Roslaniec** [comment]
Not directly.
But you can create your own wrapper with such functionality.
First you need to get metadata from PreparedStatement:
`std::unique_ptr<ResultSet> rs(stmt->result_metadata());`
Then you can use: 
```
const size_t count = stmt->field_count();
for (unsigned i = 0; i < count && rs; ++i) {
    MYSQL_FIELD * field = rs->fetch_field_direct(i);
}
```
to retrieve MYSQL_FIELD, which contains "name".

https://dev.mysql.com/doc/refman/8.0/en/c-api-optional-metadata.html
https://dev.mysql.com/doc/refman/8.0/en/c-api-data-structures.html
