### ISSUE TITLE
std::min on bind.cpp

### ISSUE THREAD

**Issue by iamhaiwen** [Roslaniec/MariaCpp#8]
[  4%] Building CXX object src/CMakeFiles/mariacpp.dir/bind.cpp.o
/root/MariaCpp-master/src/bind.cpp: In member function ‘long unsigned int MariaCpp::Bind::data_length() const’:
/root/MariaCpp-master/src/bind.cpp:178:49: error: no matching function for call to ‘min(const long unsigned int&, size_t)’
  178 |     return std::min(_length, _buffer.size(_heap));

use GCC 9.3 on linux x86

std::min(_length, _buffer.size(_heap)); =>std::min《unsigned long》(_length, _buffer.size(_heap));

**Comment by githaiwen** [comment]
std::min(_length, _buffer.size(_heap)); =>std::min<unsigned long>(_length, _buffer.size(_heap));

**Comment by Roslaniec** [comment]
Thank you for the report.
Now it's fixed with latest commit.
