### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by q1f3** [Roslaniec/MariaCpp#9]
when program run MariaCpp::scoped_library_init maria_lib_init returned Segmentation fault (core dumped)

`Type "apropos word" to search for commands related to "word"...
Reading symbols from main...(no debugging symbols found)...done.
[New LWP 1445188]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
Core was generated by ./main'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strcmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:101
101             vmovdqu (%rdi), %ymm1
`

Could you help me?

**Comment by Roslaniec** [comment]
Please attach the code.

**Comment by q1f3** [comment]
> Please attach the code.

int main()
{
MariaCpp::scoped_library_init maria_lib_init;
}

-L/usr/local/lib -lmariacpp -L/usr/lib64 -lmariadb

**Comment by Roslaniec** [comment]
No, this is not a problem of MariaCpp. 
This must be a problem with your specific build. 
Looks like you are trying to run your code on some older CPU which is not supporting specific instructions.
Make sure that all the libraries on your OS are build for your CPU.
